# This is a basic workflow to help you get started with Actions

name: Notify about commit streak

# Controls when the workflow will run
on:
  schedule:
    # Runs at 14:00 UTC every day." (see https://crontab.guru)
    - cron: '0 14 * * *'

jobs:
  push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: Send Push Notification
      uses: techulus/push-github-action@v1.0.0
      env:
        API_KEY: ${{ secrets.PUSH_API_KEY }}
        MESSAGE: "You haven't commited today. Don't lose your commit streak 🚀"
